### ISSUE TITLE
gradle 1.2 issue

### ISSUE THREAD

**Issue by nagkumar** [SeongUgJung/gradle-play-publisher#5]
When I include this plugin and run gradle

I see this error. this plugin seems to work fine in gradle 2.0 but not in gradle 1.2. However android uses only gradle 1.2, so how to use this plugin in android builds
- What went wrong:
  java.lang.NoSuchMethodError: com.google.common.hash.HashCode.fromString(Ljava/la
  ng/String;)Lcom/google/common/hash/HashCode;
  > com.google.common.hash.HashCode.fromString(Ljava/lang/String;)Lcom/google/comm
  on/hash/HashCode;

**Comment by nick-fedesna** [comment]
try adding:

```
    buildscript.dependencies {
        classpath 'com.google.guava:guava:15.0'
    }
```
